# Generated by Django 5.1.3 on 2024-11-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_atividade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='selos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizado', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.atividade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaSelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ganho', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.pessoa')),
                ('selo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.selo')),
            ],
        ),
    ]
