# Generated by Django 5.1.3 on 2024-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao_app', '0004_selo_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='selo',
            name='criterio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
